{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cpi-delta-registry.serviceAccountName" . }}
  namespace: customer-{{ .Values.global.customer.name }}
  labels:
    {{- include "cpi-delta-registry.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
